/***************************************************************
 ** Copyright (C) 2021 Aron Homberg
 **
 ** You may also use this code under the terms of the 
 ** GPL v3 (see www.gnu.org/licenses).
 ** AUDIOAPP IS PROVIDED "AS IS" WITHOUT ANY WARRANTY, AND ALL 
 ** WARRANTIES, WHETHER EXPRESSED OR IMPLIED, INCLUDING 
 ** MERCHANTABILITY AND FITNESS FOR PURPOSE, ARE DISCLAIMED.
 ***************************************************************/

#ifndef CONSTANTS_H_
#define CONSTANTS_H_

#include <JuceHeader.h>

// the version.h file is auto-generated by CMake (see version.h.in)
#include "version.h"

// current version of serialization
#define APP_SERIALIZE_CURRENT_VERSION  1

// used for properties file
#define APP_APP_NAME "YOUR_APP_NAME"
#define APP_CO_NAME  "YOUR_COMPANY"

// for help button
#define APP_HELP_URL  "https://about:blank"
#define APP_WEBSITE_URL  "https://about:blank"

#define APP_RESIZE_MSG "UI was resized. Depending on your host application, you might need to restart Audioapp to properly adjust the window size"

#endif
